src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path

from core.views import (
    Index,
    Login,
    Logout,
    Profile,
    QRCodeView,
    Registration,
    UpdateProfile,
    UpdateQRCode,
    VerificationView,
    generate_qr,
    multithreading,
    send_verification_sms,
)

app_name = "core"

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("profile/", Profile.as_view(), name="profile"),
    path("profile/update/<str:pk>", UpdateProfile.as_view(), name="update_profile"),
    # path("generate_qr/", generate_qr, name="generate_qr"),
    # path("multithreading/", multithreading, name="multithreading"),
    path("qr/<str:hash>/", QRCodeView.as_view(), name="qr_code_view"),
    path("qr/update/<str:pk>/", UpdateQRCode.as_view(), name="update_qr_code"),
    path("send_verification_sms/", send_verification_sms, name="send_verification_sms"),
    path("verification/", VerificationView.as_view(), name="verification"),
]

src/templates/user/user_login.html
{% extends "index/index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" style="width: 25em; align-content: center; margin: auto;">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type="submit" value="Login">Login</button>
    </form>
    <br>
    <p class="mb-0 text-white-50">Haven`t registered yet?<br><a href="{% url "core:registration" %}">You can do it
        right now!</a></p>
    <br>
{% endblock content %}

src/templates/user/user_profile.html
{% extends "index/index.html" %}
{% block content %}
    <table>
        <td>
            <li>{{ user.phone }}</li>
        </td>
        <td>
            <li><a href="{% url "core:update_profile" user.pk %}">Change</a></li>
        </td>
    </table>
    <br>
    {% if qr_codes %}
        <table>
            <tr>My QR-Codes</tr>
            {% for qr_code in qr_codes %}
                <tr>
                    <td>
                        <li><a href="{% url "core:qr_code_view" qr_code.hash %}">
                            {% if qr_code.title %}
                                {{ qr_code.title }}
                            {% else %}
                                My Car
                            {% endif %}
                        </a></li>
                    </td>
                    <td>
                        <li><a href="{% url "core:update_qr_code" qr_code.hash %}">Update</a></li>
                    </td>
                </tr>

            {% endfor %}
        </table>
    {% endif %}
{% endblock content %}

src/templates/user/user_registration.html
{% extends "index/index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" style="width: 25em; align-content: center; margin: auto;">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Register</button>
    </form>
{% endblock content %}

src/templates/user/user_update.html
{% extends "index/index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" style="width: 25em; align-content: center; margin: auto;">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Update</button>
    </form>
{% endblock content %}