src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path

from core.views import (
    Index,
    Login,
    Logout,
    Profile,
    QRCodeView,
    Registration,
    UpdateProfile,
    UpdateQRCode,
    VerificationView,
    generate_qr,
    multithreading,
    send_verification_sms,
)

app_name = "core"

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("profile/", Profile.as_view(), name="profile"),
    path("profile/update/<str:pk>", UpdateProfile.as_view(), name="update_profile"),
    # path("generate_qr/", generate_qr, name="generate_qr"),
    # path("multithreading/", multithreading, name="multithreading"),
    path("qr/<str:hash>/", QRCodeView.as_view(), name="qr_code_view"),
    path("qr/update/<str:pk>/", UpdateQRCode.as_view(), name="update_qr_code"),
    path("send_verification_sms/", send_verification_sms, name="send_verification_sms"),
    path("verification/", VerificationView.as_view(), name="verification"),
]

src/templates/index/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>

    <title>QR-Code</title>

    <link rel="icon" type="image/x-icon" href="{% static "assets/favicon.ico" %}"/>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
</head>
<body>
<section id="hero">
    <div class="hero-container">
        <div class="hero-container-center">
            {% if user.is_authenticated %}
                <ul>
                    <li><a href="{% url "core:logout" %}">Logout</a></li>
                    <li><a href="{% url "core:profile" %}">Profile</a></li>
                </ul>
            {% else %}
                <a href="{% url "core:login" %}">Login</a>
            {% endif %}
            {% block content %}
            {% endblock content %}
        </div>
    </div>
</section>
</body>
</html>

src/templates/index/verification.html
{% extends "index/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" style="width: 25em; align-content: center; margin: auto;">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <!>
        <!>
        <!- ADD TIMER FOR SENDING AN SMS ->
        <!>
        <!>
        <button><a href="{% url "core:send_verification_sms" %}">Send Verification code</a></button>
        <br><br>
        <button type="submit">Register</button>
    </form>
{% endblock content %}